version: '3'
services:
  name-db:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    image: postgres:11
    ports:
      - 0.0.0.0:7200:5432
  pubnow-backend:
    build: '.'
    depends_on:
      - name-db
    environment:
      - DB_URI=postgres://root:password@name-project/db?charset=UTF8
    ports:
      - '7101:7101'
    volumes:
      - .:/opt/app
